language: java

jdk:
  - openjdk8
services:
  - docker

cache:
  directories:
  - $HOME/.m2

  
script: 
  - make build
  - make build-container-ci
  - make run-container-ci
  - make load-heap; make load-heap; make load-heap
  - make heapdump-ci

