language: java

jdk:
  - openjdk8

cache:
  directories:
  - $HOME/.m2

  
script: 
  - make build-container
  - make run-container-ci
  - make load-heap; make load-heap; make load-heap
  - make heapdump-ci

