language: java

jdk:
  - openjdk8

cache:
  directories:
  - $HOME/.m2

  
script: make build-container
script: make run-container-ci
script: make load-heap; make load-heap; make load-heap
script: make heapdump-ci

